/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("alkoholspiele.kotlin-library-conventions")
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.1")
}